Add new ConcurrentMap backend for TruffleRuby
ruby-concurrency/concurrent-ruby pull request #907
Opened 2021-05-06 13:43 UTC by wildmaples

We've created a new backend for more efficient mapping on TruffleRuby using [Java's ConcurrentHashMap](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html) library - https://github.com/oracle/truffleruby/pull/2339

The new backend is faster than the previous implementation for TruffleRuby, `AtomicReferenceMapBackend`. And also [faster than MRI and JRuby](https://github.com/oracle/truffleruby/pull/2339#issuecomment-833104880): 
> 675% relative to MRI and 539% relative to JRuby.

## Changes
* Add a `TruffleRubyMapBackend` that inherits from the new `TruffleRuby::ConcurrentMap`
* Use the `TruffleRubyMapBackend` backend for `Concurrent::Map` on TruffleRuby if available

## Testing
The new backend has been tested locally and passes the `map_spec` on this gem

2021-05-07 23:00 UTC, chrisseaton requested changes

2021-05-07 23:00 UTC, chrisseaton commented
Sorry didn't realise I left my only comment as 'pending'!

2021-05-07 23:38 UTC, chrisseaton approved these changes
Thanks!

2021-05-07 23:39 UTC, merged

2021-05-24 17:56 UTC, pitr-ch commented
@chrisseaton do you need a new release? I'll have time next week.

2021-05-24 18:05 UTC, chrisseaton commented
Yes please! I was going to reach out at some point. I was looking at trying myself but it looks fairly complicated to release. Can you please document how you do it as you go through the steps? Thanks very much.

2021-05-26 18:58 UTC, pitr-ch commented
Ok, I'll see what I can do about improving the release doc.

2021-06-03 08:09 UTC, pitr-ch commented
I've flatten the condition https://github.com/ruby-concurrency/concurrent-ruby/commit/382550c1ec453ed310cca61436288eb80eacf0d9
Release will land soon.

2021-06-05 09:17 UTC, pitr-ch commented
The build doc was updated in https://github.com/ruby-concurrency/concurrent-ruby/commit/5f06b9bc337c5de05a0960b3f87a65e03f1cd4cd

2021-06-05 13:07 UTC, pitr-ch commented
released.

2021-07-16 12:01 UTC, eregon commented
Thanks!